-- ============================================================
-- Migration 0005: Auth Updates, Unique Constraints & Recovery
-- يُنفذ في Supabase > SQL Editor
-- ============================================================

-- 1. إضافة المعرف العام (public_id) لجدول profiles
-- نستخدم BIGINT يتولد تلقائياً ليكون رقماً مميزاً (مثل 10582467913) وسهل البحث
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS public_id BIGINT GENERATED BY DEFAULT AS IDENTITY;

-- 2. تفعيل القيود الفريدة (Unique Constraints) لمنع التكرار
-- التأكد من عدم تكرار الإيميل أو رقم الهاتف في قاعدة البيانات
-- (ملاحظة: إذا كان هناك بيانات مكررة حالياً، قد يظهر خطأ، يفضل أن تكون القاعدة نظيفة)
ALTER TABLE profiles DROP CONSTRAINT IF EXISTS profiles_email_key;
ALTER TABLE profiles ADD CONSTRAINT profiles_email_key UNIQUE (email);

ALTER TABLE profiles DROP CONSTRAINT IF EXISTS profiles_phone_key;
ALTER TABLE profiles ADD CONSTRAINT profiles_phone_key UNIQUE (phone);

-- 3. إنشاء جدول طلبات استعادة الحساب (recovery_requests)
CREATE TABLE IF NOT EXISTS recovery_requests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'pending', -- الحالات: pending (قيد الانتظار), resolved (تم الحل)
  request_time TIMESTAMPTZ NOT NULL DEFAULT now(),
  resolved_at TIMESTAMPTZ,
  notes TEXT
);

-- 4. تفعيل الحماية (RLS) لجدول طلبات الاستعادة
ALTER TABLE recovery_requests ENABLE ROW LEVEL SECURITY;

-- سياسات حماية لجدول الاستعادة:
-- أ) المستخدم العادي يمكنه فقط قراءة وإضافة طلباته الخاصة
DROP POLICY IF EXISTS "Users can insert their own recovery requests" ON recovery_requests;
CREATE POLICY "Users can insert their own recovery requests"
  ON recovery_requests FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can view their own recovery requests" ON recovery_requests;
CREATE POLICY "Users can view their own recovery requests"
  ON recovery_requests FOR SELECT USING (auth.uid() = user_id);

-- ب) المالك (Owner) يمتلك صلاحيات قراءة وتحديث كل الطلبات عبر الـ Dashboard
DROP POLICY IF EXISTS "Owner can read all requests" ON recovery_requests;
CREATE POLICY "Owner can read all requests"
  ON recovery_requests FOR SELECT USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'owner')
  );

DROP POLICY IF EXISTS "Owner can update requests" ON recovery_requests;
CREATE POLICY "Owner can update requests"
  ON recovery_requests FOR UPDATE USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'owner')
  );
